### PR TITLE
Forwardref

### PR DESCRIPTION
**Pull request by martinpiper**

### CODE REVIEW

**Comment by Vascillious** [comment]
That's interesting. I wonder where you got the idea to use a placeholder first to resolve the forwards referencing problem?


plCE

**Comment by Vascillious** [comment]
Also, I wonder where you got the example code you're using to test to make sure the change works?

"Ugly code"? LOL. Putting the data after the code is the normal thing to do. 

Given you're have no programming talent it's a wonder you think you're in any position to talk about shit code.


trvoe

**Comment by Vascillious** [comment]
Have you been making it clear to people you steal people's ideas and code and pass them off as your own?

**Comment by achromaticfred** [comment]
Thank you for sharing this. It's good to see you solved the problem instead of complain about it like that idiot Trevor Manning did. No surprise he was blocked from the group after abusing people who were just trying to help, he should apologise.

This approach is much better than the simplistic "placeholder" method Trevor was getting confused about. His method would not work for this particular problem because the for loop depends on the length before length is known, so the memory position of the string changes, it is a classic circular reference. I guess Trevor Manning is just not that good at programming.

It's a shame that the original ACME repository is no more. I will definitely try to contribute to your newer ACME version because it's my preferred assembler.

**Comment by martinpiper** [comment]
> This approach is much better than the simplistic "placeholder" method Trevor was getting confused about.

Indeed. The original assembler already has the "placeholder" functionality (called "unknown" in its code) so it's not new or novel. It's a very standard approach, it's also why "placeholder" is not the solution as you rightly pointed out.

The actual important part is the bit which recognises the attempt to calculate a different, changing value where it once had calculated one it thought was definite, and to let the assembler temporarily allow that value to change instead of reporting it as an error and then to allow it to converge to a stable solution over extra passes, or report the fact it cannot converge. And with the option of extending this period when new changing values are detected.

**Pull request merged**
